### PR TITLE
edit broad and equitable access

### PR DESCRIPTION
**Pull request by bonniegee**
I'm not 100% happy with the language, but this is in the direction of what I was thinking...

### CODE REVIEW

**Comment by helrond** [comment]
How about this for a first sentence:
"Advocate for an inclusive community of researchers and research methodologies by supporting and developing systems and processes that enable all researchers to discover, evaluate and retrieve archival materials. "

Not quite sure where second sentence is going? Is it that those barriers to access affect researchers unequally, or is it that those things are barriers to access?

**Comment by p-galligan** [comment]
Yeah, I prefer @helrond 's suggestion for the first sentence. I think the second sentence was an acknowledgement of what barriers to access do exist.

**Review by p-galligan — COMMENTED** [review]
I'm with @helrond in that I don't quite know what the second sentence means. Specifically "unequally"

**Comment by HaSistrunk** [comment]
I'm taking the 2nd sentence to mean that certain barriers to access, of which those are examples, can effect users unequally. I think that's an important point to articulate in thinking about how to support broad and equitable access.

What about: "Eliminate barriers to access including processing delays, unnecessary access restrictions, and complex use policies, and recognize that such barriers affect researchers unequally." 

I like Hillel's revision of the 1st sentence.

**Comment by helrond** [comment]
OK, if the second sentence is really about stating a fact that access barriers affect different user populations asymmetrically, I'd suggest that let's lead with that as a statement, and then follow with what our actions are? That's kind of what we did in the "Invest in yourself and the profession" value and I think it works nicely.

**Comment by HaSistrunk** [comment]
I like that idea

**Review by helrond — APPROVED** [review]
👍 from me!

**Review by HaSistrunk — APPROVED** [review]

**Review by p-galligan — APPROVED** [review]
Looks good to me!

**Pull request merged**
